name: Publish Workflow
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: CPU Details
        run: lscpu
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.1.2"
      - uses: mangs/simple-release-notes-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          should_auto_update_major_tag: false
      - uses: JS-DevTools/npm-publish@v3
        with:
          access: public
          registry: https://registry.npmjs.org/
          token: ${{ secrets.NPM_TOKEN }}
