name: Pull Request Workflow
on: pull_request

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: CPU Details
        run: lscpu
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6
      # - run: echo $GITHUB_BASE_REF && git rev-parse $GITHUB_BASE_REF
      # - run: echo $GITHUB_HEAD_REF && git rev-parse $GITHUB_HEAD_REF
      # - run: echo $GITHUB_REF && git rev-parse $GITHUB_REF
      # - run: echo $GITHUB_SHA
      # - run: SOURCE_BRANCH=$(git rev-parse $GITHUB_HEAD_REF) TARGET_BRANCH=$(git rev-parse $GITHUB_BASE_REF) git diff $SOURCE_BRANCH..$TARGET_BRANCH
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.1.17"
      - run: bun install --frozen-lockfile
      - run: bun run check:environment
      - run: bun --bun run check:formatting
      - run: bun --bun run check:lint-conflicts
      - run: bun --bun run check:types
      - run: bun run lint:typescript
