name: Pull Request Workflow
on: pull_request

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: CPU Details
        run: lscpu
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: "1.0.32"
      - run: bun install --frozen-lockfile
      - run: bun run check:environment
      - run: bun --bun run check:formatting
      - run: bun --bun run check:linting:eslint
      - run: bun --bun run check:types
      - run: bun run lint:typescript
